package mx.unam.iimas.util;

import java.math.BigInteger;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

class HashString {
	
	public static byte[] getSHA(String input) throws NoSuchAlgorithmException {
		MessageDigest md = MessageDigest.getInstance("SHA-256");
		
		return md.digest(input.getBytes(StandardCharsets.UTF_8));
	} 
	
	public static String toHexString(byte[] hash) { 
		BigInteger number = new BigInteger(1, hash);
		StringBuilder hexString = new StringBuilder(number.toString(16));
		while (hexString.length() < 32) {
			hexString.insert(0, '0');
		}

		return hexString.toString();
	}

	public static void main(String ... arg) {
		try {
			System.out.println("HashCode Generated by SHA-256 for:");
			String cad = "supervisor";
			String res = toHexString(getSHA(cad));
			System.out.println("\n" + cad + " : " + res + " length=" + res.length());
		} catch (NoSuchAlgorithmException e) {
			System.out.println("Exception: " + e.getMessage());
			e.printStackTrace();
		}
	}
}


